version: '3.8'
services:
  open-devin:
    build:
      context: ./open-devin
    volumes:
      - ./shared_workspace:/workspace
    networks:
      - agent_network

  aider:
    build:
      context: ./aider
    volumes:
      - ./shared_workspace:/workspace
    networks:
      - agent_network

  tailscale:
    build:
      context: ./tailscale
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - agent_network
  ts-webserver:
    image: tailscale/tailscale:latest
    hostname: webserver1
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:infrastructure
      - TS_SERVE_CONFIG=/
    volumes:
      - tailscale-data-webserver1:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  webserver1:
      image: nginx
      network_mode: service:ts-webserver1
      depends_on:
        - ts-webserver1
volumes:
  tailscale-data-webserver1:
    driver: local
networks:
  agent_network:
    driver: bridge